config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'application#home'
  root 'application#home'
  get '/home', to: 'application#home'
  get '/contact', to: 'application#contact'
  get '/team', to: 'application#team'
  
  resources :homes
  resources :gossips
  resources :users
  resources :citys
  resources :sessions

  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { in: 3..14 }
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    validates :password, presence: true, length: { minimum: 1 }
    validates :email,

    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "You need an email address to proceed. It's mandatory." }
    belongs_to :city
    has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include SessionsHelper

    def contact
    end

    def team
    end

    def home
        @gossips = Gossip.all
    end

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end
    
      def require_login
        unless current_user
          flash[:error] = "Mauvaise combine banane"
          redirect_to sessions_path
        end
      end

end

app/controllers/citys_controller.rb
class CitysController < ApplicationController
    def show
      @user = City.find(params[:id])
    end
  end
  

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

 before_action :require_login, only: [:new, :create]

    def index 
        @gossips = Gossip.all
    end

    def create
      @gossip = Gossip.create(gossip_params)
      @gossip.user = User.find_by(id: session[:user_id])
      if @gossip.save
        flash[:success] = "Potin bien créé !"
        redirect_to root_path
      else
        render :new
      end
    end

    def show
      @gossip = Gossip.find(params[:id])
    end 

    private

    def gossip_params
       params.require(:gossip).permit(:title, :content)
    end

    def require_login
      unless current_user
        flash[:danger] = "Vous devez être connecté pour créer un potin."
        redirect_to new_session_path
      end
    end
end      

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
      # Cette méthode affiche simplement la vue du formulaire de connexion (new.html.erb)
    end
  
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to session_path(user.id)
      else
        flash.now[:danger] = 'Mauvaise combine babouim'
        render 'new'
      end
    end
  
    def destroy
      session.delete(:user_id)
      flash[:success] = "A plus bolosse"
      redirect_to new_session_path
    end
  
    before_action :authenticate_user, only: [:index]
  
    def index
      # on code quelque chose qui permet d'afficher le dashboard de l'utilisateur
    end
  
    private
  
    def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Bien joué mon singe, prend une coco et balade toi !"
      redirect_to new_session_path 
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :city_id, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
    end
end

app/views/application/contact.html.erb
<% content_for :title, "Contact" %>

<div class="container contact-form">
  <div class="row">
    <div class="col-md-6">
      <div class="contact-image">
        <img src="https://s.france24.com/media/display/c3d8bee2-0fd1-11e9-877a-005056bff430/w:980/p:16x9/e7d6dbbbc5026e23e9a14efd0b43230d.webp" alt="monkey_contact" class="img-fluid" />
      </div>
    </div>
    <div class="col-md-6">
      <form method="post">
        <h3 class="mb-4">Un mot doux ?</h3>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" name="txtName" class="form-control" placeholder="Ton nom de singe *" value="" required />
            </div>
            <div class="form-group">
              <input type="email" name="txtEmail" class="form-control" placeholder="Ton email coco *" value="" required />
            </div>
            <div class="form-group">
              <input type="tel" name="txtPhone" class="form-control" placeholder="Un mobile *" value="" required />
            </div>
            <div class="form-group">
              <input type="submit" name="btnSubmit" class="btn btn-primary" value="Go" />
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <textarea name="txtMsg" class="form-control" placeholder="Bibouuuuu" style="width: 100%; height: 150px;" required></textarea>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/application/home.html.erb
<% content_for :title, "Home" %>

<div class="row">
  <% @gossips.each do |i| %> 
    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-header" style="background-color: #007BFF; color: #fff;">
          <%= i.user.first_name %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= i.title %></h5>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/application/team.html.erb
<% content_for :title, "Team" %>

<div class="container text-center mt-5">
  <h1 class="mb-4">C'est la dream team</h1>
  <div class="team-image">
    <img src="https://media1.ledevoir.com/images_galerie/nwd_452219_311955/image.jpg" alt="team_image" class="img-fluid team-image-zoom"style="max-width: 600px;">>
  </div>
</div>

<style>
  .team-image-zoom {
    transition: transform 0.3s;
  }

  .team-image-zoom:hover {
    transform: scale(1.1);
  }
</style>

app/views/citys/show.html.erb
<p>Ville : <%= @city.city.name %></p>
<p>
  <a href="/gossips" style="background-color: #007bff; color: #fff; padding: 10px 20px; text-decoration: none; border: 2px solid #007bff; border-radius: 5px; font-weight: bold; text-align: center; display: inline-block; transition: background-color 0.3s ease, color 0.3s ease;">
  Retourner à la liste des gossips
</p>

app/views/gossips/edit.html.erb
<h1>Modifier le gossip</h1>

<%= form_for @gossip do |f| %>

 <div class="form-group">
    <label>Titre du gossip</label>
    <%= f.text_field :title, class: 'form-control' %>
 </div>

 <div class="form-group">
    <label>Commentaire du gossip</label>
    <%= f.text_area :content, class: 'form-control' %>
 </div>

 <div class="form-group">
    <button type="submit">Modier le commentaire</button>
 </div>
<% end %>
 

app/views/gossips/index.html.erb
<div class="container mt-5">
  <div class="row">
    <% @gossips.each do |gossip| %>
      <div class="col-md-4">
        <div class="card mb-4" style="min-height: 300px;">
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to "#{gossip.user.first_name}: #{gossip.title}", user_path(gossip.user) %>
            </h5>
            <p class="card-text"><%= "#{gossip.content}" %></p>
          </div>
          <div class="card-footer">
            <%= link_to "Voir plus de détails", gossip_path(gossip), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/new.html.erb
<%= form_for Gossip.new, url: gossips_path, class: "container mt-5" do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Qui' %>
    <%= f.text_field :title, class: "form-control", placeholder: 'Entrez le nom de l\'auteur' %>
  </div>

  <div class="form-group">
    <%= f.label :content, 'Commentaire' %>
    <%= f.text_area :content, class: "form-control", placeholder: 'Saisissez votre commentaire' %>
  </div>

  <%= f.submit 'Nouveau gossip', class: "btn btn-primary" %>
<% end %>

app/views/gossips/show.html.erb
<h1><%= @gossip.title %></h1>
<p><%= @gossip.content %></p>
<p>Auteur : <%= @gossip.user.first_name %></p>
<p>Ville de l'auteur : <%= @gossip.user.city.name %></p>
<p>
<a href="/gossips" style="background-color: #007bff; color: #fff; padding: 10px 20px; text-decoration: none; border: 2px solid #007bff; border-radius: 5px; font-weight: bold; text-align: center; display: inline-block; transition: background-color 0.3s ease, color 0.3s ease;">
  Retourner à la liste des gossips
</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Gossip Project</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css', media: 'all' %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body data-turbo="false" style="background-image: url('https://www.wallfizz.com/nature/ile-et-ile-deserte/6015-ile-au-paradis-WallFizz.jpg'); background-size: cover; background-repeat: no-repeat; background-attachment: fixed; background-color: rgba(0, 0, 0, 0.5);">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="<%= home_path %>">The Gossip Project</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", home_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Team", team_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Gossips", new_gossip_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Gossips", gossips_path, class: "nav-link" %>
          </li>
          <div class="navbar-nav ms-auto">
            <% if current_user %>
              <%= form_tag session_path(current_user), method: :delete, class: "nav-link" do %>
                <%= submit_tag "Logout" %>
              <% end %>
            <% else %>
              <%= link_to "Login", new_session_path, class: "nav-link" %>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-4">
    <%= yield %>
  </div>
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js' %>
</body>
</html>

app/views/users/new.html.erb
<h1>Ramène toi dans le gang</h1>

<%= form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <%= f.label :city_id, "Ville", class: "sr-only" %>
    <%= f.collection_select :city_id, City.all, :id, :name, { include_blank: "Sélectionnez une ville" }, class: "form-control" %>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Confirmation du mot de passe" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "zééééé partiiii ", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1>
<p><%= @user.last_name %></p>
<p>Email de l'auteur : <%= @user.email %></p>
<p>Son age : <%= @user.age %></p>
<p>Auteur : <%= @user.first_name %></p>
<p>Ville : <%= @user.city.name %></p>

<p>
  <a href="/gossips" style="background-color: #007bff; color: #fff; padding: 10px 20px; text-decoration: none; border: 2px solid #007bff; border-radius: 5px; font-weight: bold; text-align: center; display: inline-block; transition: background-color 0.3s ease, color 0.3s ease;">
  Retourner à la liste des gossips
</p>